// Generated by CoffeeScript 1.10.0
(function() {
  var combineNames, combineNames2;

  combineNames = function(firstName, lastName) {
    return firstName + " " + lastName;
  };

  combineNames2 = function(first, last) {
    return [first, last].join(' ');
  };

  console.log((combineNames('Norbert', 'Pozsonyi')) === 'Norbert Pozsonyi');

  console.log((combineNames2('Norbert', 'Pozsonyi')) === 'Norbert Pozsonyi');

}).call(this);
