// Generated by CoffeeScript 1.10.0
(function() {
  var getCharacterOccurenceInString;

  getCharacterOccurenceInString = function(char, str) {
    var regExp;
    regExp = new RegExp(char, 'g');
    return (str.match(regExp) || []).length;
  };

  console.log((getCharacterOccurenceInString('a', 'anna')) === 2);

  console.log((getCharacterOccurenceInString('a', 'Anna')) === 1);

  console.log((getCharacterOccurenceInString('b', 'anna')) === 0);

}).call(this);
