// Generated by CoffeeScript 1.10.0
(function() {
  var getPrice;

  getPrice = function(quantity) {
    var i, len, prices, range;
    prices = [
      {
        qty: 10,
        price: 90
      }, {
        qty: 5,
        price: 95
      }, {
        qty: 0,
        price: 100
      }
    ];
    for (i = 0, len = prices.length; i < len; i++) {
      range = prices[i];
      if (range.qty <= quantity) {
        return quantity * range.price;
      }
    }
  };

  console.log((getPrice(1)) === 100);

  console.log((getPrice(5)) === 475);

  console.log((getPrice(100)) === 9000);

}).call(this);
