// Generated by CoffeeScript 1.10.0
(function() {
  var positiveSum, positiveSum2;

  positiveSum = function(arr) {
    var reduceCallback;
    reduceCallback = function(memo, curr) {
      return memo + (curr > 0 ? curr : 0);
    };
    return arr.reduce(reduceCallback, 0);
  };

  positiveSum2 = function(arr) {
    return arr.filter(function(e) {
      return e > 0;
    }).reduce(function(m, c) {
      return m + c;
    });
  };

  console.log((positiveSum([1, 2, 3, 4, 5])) === 15);

  console.log((positiveSum([-1, 2, 3, 4, -5])) === 9);

  console.log((positiveSum2([1, 2, 3, 4, 5])) === 15);

  console.log((positiveSum2([-1, 2, 3, 4, -5])) === 9);

}).call(this);
