// Generated by CoffeeScript 1.10.0
(function() {
  var min;

  min = function(arr, toReturn) {
    var minimum;
    minimum = Math.min.apply(Math, arr);
    if (toReturn === 'index') {
      return arr.indexOf(minimum);
    } else {
      return minimum;
    }
  };

  console.log((min([1, 2, 3, 4, 5])) === 1);

  console.log((min([1, 2, 3, 4, 5], 'index')) === 0);

}).call(this);
