// Generated by CoffeeScript 1.10.0
(function() {
  var format, text;

  format = function(text, width) {
    var i, j, lastLine, lines, ref, word, words;
    words = text.split(' ');
    lines = [];
    lastLine = words[0];
    for (i = j = 1, ref = words.length; 1 <= ref ? j < ref : j > ref; i = 1 <= ref ? ++j : --j) {
      word = words[i];
      if ((lastLine + ' ' + word).length > width) {
        lines.push(lastLine);
        lastLine = word;
      } else {
        lastLine += ' ' + word;
      }
    }
    lines.push(lastLine);
    return lines.join('\n');
  };

  text = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nec consectet ur risus. Cras vel urna a tellus dapibus consequat. Duis bibendum tincidunt viverra. Ph asellus dictum efficitur sem quis porttitor. Mauris luctus auctor diam id ultrices. Pra esent laoreet in enim ut placerat. Praesent a facilisis turpis.';

  console.log(format(text, 30));


  /*
  Lorem ipsum dolor sit amet,        
  consectetur adipiscing elit.       
  Aliquam nec consectet ur           
  risus. Cras vel urna a tellus      
  dapibus consequat. Duis            
  bibendum tincidunt viverra. Ph     
  asellus dictum efficitur sem       
  quis porttitor. Mauris luctus      
  auctor diam id ultrices. Pra       
  esent laoreet in enim ut           
  placerat. Praesent a facilisis     
  turpis.
   */

}).call(this);
