// Generated by CoffeeScript 1.10.0
(function() {
  var a1, a2, a3, a4, comp,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  comp = function(array1, array2) {
    if ((!Array.isArray(array1)) || (!Array.isArray(array2))) {
      return false;
    }
    if (array1.length !== array2.length) {
      return false;
    }
    return !array1.some(function(num, i) {
      var ref, ref1;
      return (ref = num * num, indexOf.call(array2, ref) < 0) || (ref1 = Math.sqrt(array2[i]), indexOf.call(array1, ref1) < 0);
    });
  };

  a1 = [121, 144, 19, 161, 19, 144, 19, 11];

  a2 = [11 * 11, 121 * 121, 144 * 144, 19 * 19, 161 * 161, 19 * 19, 144 * 144, 19 * 19];

  a3 = [121, 144, 19, 161, 19, 144, 19, 11];

  a4 = [11 * 9999999, 121 * 121, 144 * 144, 19 * 19, 161 * 161, 19 * 19, 144 * 144, 19 * 19];

  console.log((comp(a1, a2)) === true);

  console.log((comp(a3, a4)) === false);

  console.log((comp([], null)) === false);

  console.log((comp([], [])) === true);

}).call(this);
